# Generated by Django 5.0.3 on 2024-04-01 19:58

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('genre', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), size=None)),
                ('director', models.CharField(max_length=100)),
                ('cast', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), size=None)),
                ('plot', models.TextField()),
                ('rating', models.DecimalField(decimal_places=1, max_digits=2)),
                ('poster', models.ImageField(blank=True, default='api/static/api/images/posters/default_poster.jpg', upload_to='api/static/api/images/posters/')),
            ],
        ),
    ]
